<?php include '../../header.php'; echo head('List of Changes in SSPP Since DR8 - SSPP'); ?>

<p><a href="dr9/spectro/sspp.php"><b>[Back to main SSPP page]</b></a></p>

<p>The SSPP has been refined and modified with each new SDSS data release in order to
provide more accurate estimates of the stellar atmospheric parameters. Here, we
describe major changes and improvements made to the SSPP since Data Release 8
(DR8).</p>

<ul>
<li> Metallicity determined from Auto-correlation Function (ACF), 
     Ca II triplet line index (CaIIT) method, and <a href="dr9/spectro/sspp_methods.php">ANNSR</a> is no longer 
     reported and does not contribute to the best metallicity estimate for each star. </li>
<li>Gravity estimate from (MgH) and (CaI2) line index methods and <a href="dr9/spectro/sspp_methods.php">k24</a> is 
    not reported any more and does not contribute to the best gravity estimate 
    for each star.</li>
<li><a href="dr9/spectro/sspp_methods.php">NGS1</a> and <a href="dr9/spectro/sspp_methods.php">CaIIK1</a> make use of a new grid of synthetic spectra
    generated with &alpha;-enhanced Kurucz model atmospheres and with variable
    micro-turbulence velocity with surface gravities. The adopted relation is
    V<sub>t</sub>=-0.345&times;log <i>g</i>+2.225, and this relation is derived
    from a sample of high-resolution spectra.</li>
<li>NGS2 utilizes a new grid of synthetic spectra
    created with &alpha;-enhanced Kurucz model atmospheres with
    micro-turbulence velocity fixed at 1 km/s.</li>
<li>The grid of synthetic spectra used in the <a href="dr9/spectro/sspp_methods.php">NGS1</a>, 
    <a href="dr9/spectro/sspp_methods.php">CaIIK1</a>, and
    estimates is extended to [Fe/H]=-4.5 and [Fe/H]=+1.0 in order 
    to improve the estimates at low metallicity and above solar metallicity. </li>
<li>Instead of linear interpolation, cubic spline interpolation is implemented 
    for <a href="dr9/spectro/sspp_methods.php">k24</a>, <a href="dr9/spectro/sspp_methods.php">ki13</a>, 
    <a href="dr9/spectro/sspp_methods.php">NGS1</a>, <a href="dr9/spectro/sspp_methods.php">NGS2</a>, and 
    <a href="dr9/spectro/sspp_methods.php">CaIIK1</a> during &chi;<sup>2</sup> minimization. 
    That is, a new trial synthetic spectrum to calculate 
    &chi;<sup>2</sup> value is generated by interpolating fluxes from existing 
    grid of synthetic spectra with a cubic spline function.</li>
<li> If more than 5 % of a region of a spectrum used by a
     particular parameter estimation method has the inverse variance of the spectrum flux
     array set to zero, no parameter estimate is reported for that particular
     method. This was done to improve the reliability of the parameter
     estimates, especially at very low metallicity.</li>
<li> A new set of <a href="dr9/spectro/sspp_methods.php">g-r and S/N limits</a> is introduced for individual
     methods. These changes were made after evaluating the accuracy of the
     individual estimators in the SSPP estimates for a set of synthetic spectra with
     realistic noise properties covering the range of g-r and S/N in the
     SEGUE data, as well as the high resolution and cluster spectra.</li>
<li> New neural networks trained on new grid of synthetic spectra and the DR8
     parameters are implemented for <a href="dr9/spectro/sspp_methods.php">ANNSR</a> and 
     <a href="dr9/spectro/sspp_methods.php">ANNRR</a>, respectively.</li>
<li> The color-based temperature estimates by T<sub>K</sub>, T<sub>G</sub>, and T<sub>I</sub> 
     are not reported and do not contribute to the best temperature estimate. </li>
<li> Effective temperature based on the <a href="dr9/spectro/sspp_irfm.php">InfraRed Flux Method (IRFM)</a> 
     is estimated, using g-i, log <i>g</i>, and [Fe/H] from <a href="dr9/spectro/sspp_methods.php">NGS1</a>.</li>
<li> A comparison with the DR8 stellar parameters indicates that the DR9
     <var>T</var><sub>eff</sub> is, on average, higher by ~60 K, the DR9 log <i>g</i> 
     is lower by ~0.2 dex, and the metallicity does not change significantly (less than 0.02 index).
     The temperature shift occurs because we adopt the IRFM temperature scale to
     calibrate each temperature estimate in the SSPP. The reason for the gravity
     shift can be partly explained by the new log <i>g</i> values from the re-analysis of the
     high-resolution spectra, which are 0.13 dex lower than the previous high-resolution 
     values. Another contribution to the shift in log <i>g</i> is the new grid of synthetic spectra for 
     <a href="dr9/spectro/sspp_methods.php">NGS1</a>, <a href="dr9/spectro/sspp_methods.php">NGS2</a>, 
     and <a href="dr9/spectro/sspp_methods.php">CaI</a>. However, the biggest causes of this shift are the retirement of the
     gravity estimates by MgH and CaI2 line index methods, which
     consistently deliver much higher (and less accurate) log <i>g</i> estimates that the
     other estimators in the DR8 SSPP.</li>
</ul>
<?php echo foot(); ?>
