<?php include '../../header.php'; echo head('Algorithms: Image masks'); ?>

<p>Jump to:</p>
<p><a href="dr8/algorithms/masks.php#intro">[Intro]</a>&nbsp;<a href="dr8/algorithms/masks.php#bleed_bright">[BLEEDING and BRIGHT_STAR]</a>&nbsp;<a href="dr8/algorithms/masks.php#trail">[TRAIL]</a>&nbsp;<a href="dr8/algorithms/masks.php#hole">[HOLE]</a>&nbsp;  <a href="dr8/algorithms/masks.php#seeing">[SEEING]</a></p>


<h2 id="intro">Introduction</h2>

<p><b>NOTE: we do not release the imaging masks in DR8. They will be
released as part of DR9.</b></p>

<p>
Imaging masks are intended to define those survey areas which
one may wish to exclude from scientific analysis for a number of
reasons.  These differ from the <code>photo</code> imaging mask in the
<code>fpM</code> files. There are 5 different mask types, as follows: </p>

<table class="common">
  <tr><th>Type</th><th>Meaning</th></tr>
  <tr><td>0</td> <td>BLEEDING</td></tr>
  <tr><td>1</td> <td>BRIGHT_STAR</td></tr>
  <tr><td>2</td> <td>TRAIL</td></tr>
  <tr><td>3</td> <td>HOLE</td></tr>
  <tr><td>4</td> <td>SEEING</td></tr>
</table>

<p>These masks thus allow one to identify and exclude bright stars and
their associated bleeding columns, trails caused by meteors and
satellites, a small number of survey "holes" which have
unacceptable data, as well as regions with bad seeing.
These masks may of course be used in any science analysis to check
the effects of excluding/including potentially problematic survey
areas, but are likely to be most relevant and useful for studies
of large-scale structure. </p>

<p>Note that the masks are in the form of convex polygons, and they are
generated separately for each of the 5 filters of each survey field.
The masks are also solely contained within the PRIMARY survey
area.</p>

<p><a href="dr8/algorithms/masks.php#Top">[Back to top]</a></p>


<h2 id="bleed_bright">BLEEDING and BRIGHT_STAR masks</h2>

<p>These masks are intended to define those imaging areas covered by
large saturated stars (approximate radius &gt;= 1 arcmin), with
significant bleeding columns, which are expected to cause problems in
photometry, target selection, etc.</p>

<p>The masks are based on the original masks contained in the fpM files
generated by the frames pipeline.  Specifically, the fpM files contain
masks of saturated pixels as well as masks of detected objects.  We
look for those saturated pixel masks which overlap with a
corresponding detected object mask, but consider only those cases in
which the object mask has an approximate radius &gt;= 1 arcmin, so that
we are picking out primarily large saturated stars.  The radius is
approximate, as it's defined simply as the maximum among the distances
between the object mask vertices and the unweighted object mask
centroid.  We also make a further cut that the length of the saturated
pixel mask should be at least half the length of the object mask, so
that we are selecting those objects with significant bleeding columns.
The final BLEEDING column mask used corresponds to the original fpM
saturated pixel mask, while the BRIGHT_STAR mask corresponds to the
original fpM object mask.</p>


<p><a href="dr8/algorithms/masks.php#Top">[Back to top]</a></p>
<h2 id="trail">TRAIL masks</h2>

<p>These masks are intended to define those imaging areas covered by
trails caused by meteors, satellites, and the like.</p>

<p>We start with the detected object masks in the fpM files, and then
apply a number of simple criteria to select objects which are long and
thin.  We first construct a rectangular bounding box around the object
mask and check that its diagonal extends over a significant fraction of
a field, specifically that the diagonal is &gt; 1361/2 pixels (= 4.5
arcmin), i.e., over half the row extent of a single CCD field.  Then
we check that the mask is thin, specifically if either the ratio of
the long to short side of the bounding rectangle is &gt; 3, or the
fraction of the bounding rectangle actually filled by mask pixels is &lt;
0.33.  Finally we verify that the object mask doesn't already
correspond to a BRIGHT_STAR mask, so that long bleeding columns are
excluded.  The final TRAIL masks correspond to those fpM object masks
which pass these criteria.</p>

<p>Note that the above criteria for defining TRAIL masks are somewhat
arbitrary and will not be perfect in catching all trails in the
imaging data.  The precise criteria used may also be further refined
in the future.  Nonetheless, these TRAIL masks may be used to assess
if removing obvious trails in the data would significantly impact a
particular science analysis.</p>

<p><a href="dr8/algorithms/masks.php#Top">[Back to top]</a></p>
<h2 id="hole">HOLE masks</h2>

<p>These masks denote holes in the survey and indicate fields where
the data quality is unacceptable, so that the imaging data
there should not be used.  Fields may be set to hole for
a number of reasons, including problems with non-photometricity
or with astrometry, as well as software processing problems
such as photo frames timeouts, most often caused by the presence
of very bright stars in a field.</p>

<p><a href="dr8/algorithms/masks.php#Top">[Back to top]</a></p>
<h2 id="seeing">SEEING masks</h2>

<p>These masks contain a measure of the seeing as a function of position
in the survey.  SEEING masks are made for each filter in each
survey field, or more precisely, on a nominal 3 by 5 subgrid for each
CCD field (3 along the scan direction, 5 perpendicular to the scan).
Each SEEING mask is thus nominally 1361/3 pixels by 2048/5 pixels,
or 3.0 arcmin by 2.7 arcmin, but may be smaller in area once the
PRIMARY survey area cuts are applied.  </p>

<p>We use the psField files to reconstruct the PSF for the appropriate
filter, at each of the 3 by 5 subgrid positions in each CCD field.
The seeing value, or PSF width, is then determined from </p>
<pre>    seeing = 0.663 * 0.400 * sqrt(neff)  arcsec</pre>
<p>where neff is the effective area of the PSF, as given by
neff = (sum I)^2/sum(I^2), where the sums are over the counts I of
the PSF.</p>

<p>One may then choose to define a desired threshold for bad seeing,
and use the SEEING masks to exclude survey regions that fail the
seeing cut.  Of course the bad seeing threshold may be varied to
assess the effect of the threshold value on the particular science
analysis at hand.  An example would be to see how a particular
large-scale structure statistic is affected by the precise choice
of the bad seeing threshold.</p>


<p><a href="dr8/algorithms/masks.php#Top">[Back to top]</a></p>

<?php echo foot(); ?>
